apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  replicas: 3
  selector:
   matchLabels:
    app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp2
        image: gcr.io/secure-totality-266019/kubernetesrepos:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-svc
  labels:
    app: webapp2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: webapp2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp2
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 3
